name: "Hello world workflow"

# controls when the actions will run. Triggers the workflow on push some to mster and production branches
on:
    push:
        branches:
            - master
            - production


jobs:
    hello_world:
        runs_on: ubuntu-latest
        steps:
            - name: "Print hello world"
            run: echo "Hello world"